version: '2'
services:
  redis:
    build: .
    ports:
     - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/redis/redis.conf
      - ./redis.log:/usr/local/redis/redis.log
      - ./data:/usr/local/redis/data
    restart: always
    container_name: redis