version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: mysql

  nginx:
    depends_on: 
      - php
    build: ./nginx
    volumes:
      - /data0/www:/data0/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log/access.log:/var/log/nginx/access.log
      - ./nginx/log/error.log:/var/log/nginx/error.log
    restart: always
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx

  php:
    depends_on:
      - mysql
      - redis
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./php/php-fpm.conf:/etc/php-fpm.conf
      - ./php/www.conf:/etc/php-fpm.d/www.conf
      - ./php/php.ini:/etc/php.ini
      - /data0/www:/data0/www
    restart: always
    container_name: php

  redis:
    build: ./redis
    ports:
     - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log
      - ./redis/data:/usr/local/redis/data
    restart: always
    container_name: redis 
  
hexo:
    build: ./hexo
    ports:
     - "4000:4000"
    volumes:
     - /data0/www/blog:/blog
    restart: always
    container_name: hexo
